// https://raw.githubusercontent.com/bitburner-official/bitburner-src/dev/src/Programs/Enums.ts

export enum CompletedProgramName {
  nuke = "NUKE.exe",
  bruteSsh = "BruteSSH.exe",
  ftpCrack = "FTPCrack.exe",
  relaySmtp = "relaySMTP.exe",
  httpWorm = "HTTPWorm.exe",
  sqlInject = "SQLInject.exe",
  deepScan1 = "DeepscanV1.exe",
  deepScan2 = "DeepscanV2.exe",
  serverProfiler = "ServerProfiler.exe",
  autoLink = "AutoLink.exe",
  formulas = "Formulas.exe",
  bitFlume = "b1t_flum3.exe",
  flight = "fl1ght.exe",
}

// https://raw.githubusercontent.com/bitburner-official/bitburner-src/dev/src/Faction/Enums.ts
export enum FactionName {
  Illuminati = "Illuminati",
  Daedalus = "Daedalus",
  TheCovenant = "The Covenant",
  ECorp = "ECorp",
  MegaCorp = "MegaCorp",
  BachmanAndAssociates = "Bachman & Associates",
  BladeIndustries = "Blade Industries",
  NWO = "NWO",
  ClarkeIncorporated = "Clarke Incorporated",
  OmniTekIncorporated = "OmniTek Incorporated",
  FourSigma = "Four Sigma",
  KuaiGongInternational = "KuaiGong International",
  FulcrumSecretTechnologies = "Fulcrum Secret Technologies",
  BitRunners = "BitRunners",
  TheBlackHand = "The Black Hand",
  NiteSec = "NiteSec",
  Aevum = "Aevum",
  Chongqing = "Chongqing",
  Ishima = "Ishima",
  NewTokyo = "New Tokyo",
  Sector12 = "Sector-12",
  Volhaven = "Volhaven",
  SpeakersForTheDead = "Speakers for the Dead",
  TheDarkArmy = "The Dark Army",
  TheSyndicate = "The Syndicate",
  Silhouette = "Silhouette",
  Tetrads = "Tetrads",
  SlumSnakes = "Slum Snakes",
  Netburners = "Netburners",
  TianDiHui = "Tian Di Hui",
  CyberSec = "CyberSec",
  Bladeburners = "Bladeburners",
  ChurchOfTheMachineGod = "Church of the Machine God",
  ShadowsOfAnarchy = "Shadows of Anarchy",
}
